version: '3.8'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.12.16.0/22
services:
  hedge-bot:
    build: .
    container_name: hedge-bot
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./main.py:/app/main.py:ro
      - ./__init__.py:/app/__init__.py:ro
      - ./pacifica_client.py:/app/pacifica_client.py:ro
      - ./ewma_hedge_ratio.py:/app/ewma_hedge_ratio.py:ro
      - ./hedge_ratio.py:/app/hedge_ratio.py:ro
      - ./config.json:/app/config.json:ro
      - ./pacifica_sdk:/app/pacifica_sdk:ro
      - ./state.json:/app/state.json
      - ./hedge_bot.log:/app/hedge_bot.log
